name: test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.version }}
    - uses: actions/cache@v2
      name: Restore pip cache
      with:
        path: ~/.cache/pip
        key: pip-${{ hashFiles('requirements.txt', 'dev-requirements.txt') }}
        restore-keys: |
          pip-
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt -r dev-requirements.txt
    - name: Test with pytest
      run: |
        pytest
